apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hireverse-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx  
  rules:
    - host: api.hireverse.dev  
      http:
        paths:
          - path: /api/user/?(.*)
            pathType: ImplementationSpecific  
            backend:
              service:
                name: user-srv
                port:
                  number: 5001

